name: "build"
on:
  push:
    branches:
      - master
    pull_request:
      - master

jobs:
  python3_x:
    strategy:
      fail-fast: false
      matrix:
        python_version: [7, 8, 9, 10, 11]
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/harmening/pyreite:py3.${{ matrix.python_version }}
      credentials:
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_TOKEN2 }}
      volumes: 
        - ${{ github.workspace }}:/pyreite
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install pyreite
        run: |
          cd /pyreite
          python setup.py develop
      - name: Install test suite
        run: |
          pip install pytest
          pip install coverage
          pip install codecov
          pip install pytest-codecov
      - name: Run pytest
        run: |
          cd /pyreite
          coverage run -m pytest tests
          coverage report -m
          coverage xml
          codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: /coverage.xml
